version: '3.8'

services:

  postgres:
    image: postgres:16

    container_name: postgres

    environment:
      POSTGRES_DB: studentdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

    ports:
      - "5432:5432"

    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d studentdb"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  backend:

    build: ./backend

    container_name: backend

    ports:
      - "8080:8080"

    depends_on:
      postgres:
        condition: service_healthy

    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/studentdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password

    restart: on-failure

  frontend:

    build: ./frontend

    container_name: frontend

    ports:
      - "80:80"

    depends_on:
      - backend